In [1]:
import pandas as pd
import numpy as np

import metrics_summary as ms

In [2]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

## KNN

In [3]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier()
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(knn, X_train, y_train)

[[49696  1042]
 [ 5596   403]]
Kappa Score: 0.07010368488854712
Accuracy Score: 0.8830040361668753
Precision: 0.27889273356401384
Recall: 0.06717786297716286
F1 Score: 0.10827512090274047
AUC Score: 0.5233204936313541
Average Accuracy Score: 0.8833940210782906
Average Precision Score: 0.2742325285600979
Average Recall Score: 0.0624464802581658
Average F1 Score: 0.8833940210782906
[0.88286614 0.88304743 0.88426849]
Average AUC Score: 0.607319986229447
[0.60218056 0.6117598  0.60801959]


#### KNN Using SMOTE

In [4]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
pipeline = Pipeline(steps=[('over', SMOTE()), ('model', KNeighborsClassifier())])
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(pipeline, X_train, y_train)

[[35062 15676]
 [ 2924  3075]]
Kappa Score: 0.10511455898086697
Accuracy Score: 0.6721715987803374
Precision: 0.16399125379979734
Recall: 0.5125854309051509
F1 Score: 0.2484848484848485
AUC Score: 0.6018128384373206
Average Accuracy Score: 0.6727524006709228
Average Precision Score: 0.16112503701498396
Average Recall Score: 0.4981423008370358
Average F1 Score: 0.6727524006709228
[0.67234698 0.6738426  0.67206762]
Average AUC Score: 0.6242381306650965
[0.62547763 0.62324047 0.62399629]
