In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import metrics_summary as ms

In [18]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

In [19]:
np.random.seed(170)

## Logistic Regression

In [20]:
# check p-values of features
import statsmodels.api as sm
logit_model = sm.Logit(y_train, X_train)
result = logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.250358
         Iterations 9
                             Results: Logit
Model:                 Logit              Pseudo R-squared:   0.258     
Dependent Variable:    y                  AIC:                66841.8354
Date:                  2022-05-29 03:23   BIC:                69554.6286
No. Observations:      132386             Log-Likelihood:     -33144.   
Df Model:              276                LL-Null:            -44677.   
Df Residuals:          132109             LLR p-value:        0.0000    
Converged:             1.0000             Scale:              1.0000    
No. Iterations:        9.0000                                           
------------------------------------------------------------------------
             Coef.    Std.Err.     z     P>|z|     [0.025       0.975]  
------------------------------------------------------------------------
AB1          0.4991      0.0124  40.2394 0.0000    

The feature with p-values less than 0.05 are the significant ones. Consider getting rid of insignificant features and then fit it into the logistic regression model

In [21]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(logreg, X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[50339   399]
 [ 5721   278]]
Kappa Score: 0.06319412019362591
Accuracy Score: 0.8921338808890142
Precision: 0.41063515509601184
Recall: 0.046341056842807135
F1 Score: 0.08328340323547034
AUC Score: 0.5192385642131179


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.8939313836015295
Average Precision Score: 0.48220278972205616
Average Recall Score: 0.04136891704173939
Average F1 Score: 0.8939313836015295
[0.89412858 0.89358472 0.89408086]
Average AUC Score: 0.7855800695293395
[0.77951823 0.79113178 0.7860902 ]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [22]:
logreg_cs = LogisticRegression(max_iter=1000, class_weight="balanced")
logreg_cs.fit(X_train, y_train)
y_pred = logreg_cs.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(logreg_cs, X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[35433 15305]
 [ 1545  4454]]
Kappa Score: 0.2191708488871198
Accuracy Score: 0.7030156687875637
Precision: 0.22541626600536466
Recall: 0.7424570761793632
F1 Score: 0.34583430390558273
AUC Score: 0.7204046979698503


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.6953756257138922
Average Precision Score: 0.2200144065702135
Average Recall Score: 0.7387836908870918
Average F1 Score: 0.6953756257138922
[0.68852682 0.70463867 0.69296139]
Average AUC Score: 0.7866103484566213
[0.77580582 0.79332475 0.79070048]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### Logistic Regression using oversampled data from SMOTE

In [23]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
pipeline = Pipeline(steps=[('over', SMOTE()), ('model', LogisticRegression(max_iter=1000))])
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(pipeline, X_train, y_train)

/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[35308 15430]
 [ 1557  4442]]
Kappa Score: 0.21605923048487674
Accuracy Score: 0.7006010187355693
Precision: 0.2235305958132045
Recall: 0.740456742790465
F1 Score: 0.34339608055351556
AUC Score: 0.7181727129144095


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.6972716135905482
Average Precision Score: 0.22154594988212625
Average Recall Score: 0.7412829914302564
Average F1 Score: 0.6972716135905482
[0.69956265 0.69514378 0.69710841]
Average AUC Score: 0.788796012145836
[0.79202477 0.78783052 0.78653274]


/opt/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [ ]:
# Use variance inflation factor to identify any significant multi-collinearity
from statsmodels.stats.outliers_influence import variance_inflation_factor
X_constant = sm.add_constant(X_train, prepend=False)
vif = pd.DataFrame()
vif["Features"] = X_constant.columns
vif["VIF"] = [variance_inflation_factor(X_constant.values, i) for i in range(X_constant.shape[1])]
vif

In [ ]:
# sns.set(font_scale=1.25)
# # chis_train = pd.concat([X_train, y_train], axis=1)
# # chis_train = chis_train.rename(columns = {'T2D': 'Type 2 Diabetes', 'AB24': 'Taking Insulin', 'AB23_P1': 'Age Told To Have Diabetes', 'AB112': 'Diabetes Care Plan', 
# # 'AB25': 'Diabetic Pills', 'AB63': 'Eye Exam Dilated Pupils', 'AB114_P1': 'Confidence to Control Diabetes', 'AB28_P1': 'Doctor Checked Feet for Sores', 'AB109': 'Visited ER', 
# # 'AB113': 'Copy of Diabetes Care Plan', 'AB111': "Hospital Overnight for Diabetes"})

# corrMatrix = X_train.corr()
# plt.subplots(figsize=(24, 18))
# # g = sns.heatmap(corrMatrix, annot=True, cmap="Accent", vmin=-1, vmax=1)
# g = sns.heatmap(corrMatrix, annot=True, cmap="Accent")
# plt.title('Correlation Heatmap', size = 25)
# plt.show()

In [ ]:
from statsmodels.genmod.generalized_linear_model import GLM
from statsmodels.genmod import families

# Setup logistic regression model (using GLM method so that we can retrieve residuals)
logit_model = GLM(y_train, X_constant, family=families.Binomial())
logit_results = logit_model.fit()
print(logit_results.summary())

In [ ]:
import scipy
# Generate residual series plot
fig = plt.figure(figsize=(15,9))
ax = fig.add_subplot(111, title="Residual Series Plot",
                    xlabel="Index Number", ylabel="Deviance Residuals")

# ax.plot(X.index.tolist(), stats.zscore(logit_results.resid_pearson))
ax.plot(X_constant.index.tolist(), scipy.stats.zscore(logit_results.resid_deviance))
plt.axhline(y=0, ls="--", color='red');