In [45]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [46]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

## SMOTE

In [47]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
os = SMOTE(random_state=0)
os_X, os_y = os.fit_resample(X_train, y_train)
print(os_X.shape, os_y.shape)

(236866, 52) (236866,)


In [48]:
# split the oversample data (keeping code for now in case we need it later)
# from sklearn.model_selection import train_test_split
# os_X_train, os_X_test, os_y_train, os_y_test = train_test_split(os_X, os_y, test_size=0.30, random_state=0)
# print(os_X_train.shape, os_y_train.shape)

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.model_selection import cross_validate

# Custom function to print the metrics of the model
def display_metrics(y_test, y_pred):
    print(confusion_matrix(y_test, y_pred))
    print(f'Accuracy Score: {accuracy_score(y_test, y_pred)}')
    print(f'Precision: {precision_score(y_test, y_pred)}')
    print(f'Recall: {recall_score(y_test, y_pred)}')
    print(f'F1 Score: {f1_score(y_test, y_pred)}')

def display_crossval_scores(model, X_train, y_train):
    scoring = ['accuracy', 'precision', 'recall', 'f1_micro']

    results = cross_validate(model, X_train, y_train, scoring=scoring, cv=5)
    print(f"Average Accuracy Score: {np.mean(results['test_accuracy'])}")
    print(f"Average Precision Score: {np.mean(results['test_precision'])}")
    print(f"Average Recall Score: {np.mean(results['test_recall'])}")
    print(f"Average F1 Score: {np.mean(results['test_f1_micro'])}")

## Logistic Regression

In [50]:
# # check p-values of features
# import statsmodels.api as sm
# logit_model = sm.Logit(y_train, X_train)
# result = logit_model.fit()
# print(result.summary2())

The feature with p-values less than 0.05 are the significant ones. Consider getting rid of insignificant features and then fit it into the logistic regression model

In [60]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(random_state=0, max_iter=2000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
display_metrics(y_test, y_pred)
display_crossval_scores(logreg, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[49990   705]
 [  423  5619]]
Accuracy Score: 0.980118793732485
Precision: 0.8885199240986718
Recall: 0.9299900695134061
F1 Score: 0.9087821445900048


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.9800205416953757
Average Precision Score: 0.8844464716874597
Average Recall Score: 0.9322722421916836
Average F1 Score: 0.9800205416953757


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [52]:
# from sklearn.model_selection import cross_val_score
# cross_val_score(logreg, X_train, y_train, cv=10, scoring="accuracy")

In [53]:
# from sklearn.model_selection import RepeatedStratifiedKFold

# # define model
# model = LogisticRegression(class_weight='balanced')

# # define cross-validation
# cv = RepeatedStratifiedKFold(n_splits=10, n_repeats=3, random_state=1)

# # evaluate model
# scores = cross_val_score(model, X_train, y_train, scoring='roc_auc', cv=cv, n_jobs=-1)

# # summarize performance
# print('Mean AUROC: %.3f' % np.mean(scores))

In [54]:
logreg_cs = LogisticRegression(random_state=0, max_iter=1000, class_weight="balanced")
logreg_cs.fit(X_train, y_train)
y_pred = logreg_cs.predict(X_test)
display_metrics(y_test, y_pred)
display_crossval_scores(logreg_cs, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[49891   804]
 [   28  6014]]
Accuracy Score: 0.9853358478594215
Precision: 0.8820768553828102
Recall: 0.9953657729228732
F1 Score: 0.9353032659409021


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.9849002132357076
Average Precision Score: 0.8767134252543881
Average Recall Score: 0.9969898637325043
Average F1 Score: 0.9849002132357076


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### Logistic Regression using oversampled data from SMOTE

In [55]:
logreg_os = LogisticRegression(random_state=0, max_iter=1000)
logreg_os.fit(os_X, os_y)
y_pred = logreg_os.predict(X_test)
display_metrics(y_test, y_pred)
display_crossval_scores(logreg_os, os_X, os_y)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[49894   801]
 [   45  5997]]
Accuracy Score: 0.9850890952993637
Precision: 0.882171226831421
Recall: 0.9925521350546177
F1 Score: 0.9341121495327102


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.9907120545779916
Average Precision Score: 0.9839061208953872
Average Recall Score: 0.9977455714031706
Average F1 Score: 0.9907120545779916


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [56]:
# # Use variance inflation factor to identify any significant multi-collinearity
# from statsmodels.stats.outliers_influence import variance_inflation_factor
# X_constant = sm.add_constant(X_train, prepend=False)
# vif = pd.DataFrame()
# vif["Features"] = X_constant.columns
# vif["VIF"] = [variance_inflation_factor(X_constant.values, i) for i in range(X_constant.shape[1])]
# vif

In [57]:
# sns.set(font_scale=1.25)
# chis_train = pd.concat([X_train, y_train], axis=1)
# chis_train = chis_train.rename(columns = {'T2D': 'Type 2 Diabetes', 'AB24': 'Taking Insulin', 'AB23_P1': 'Age Told To Have Diabetes', 'AB112': 'Diabetes Care Plan', 
# 'AB25': 'Diabetic Pills', 'AB63': 'Eye Exam Dilated Pupils', 'AB114_P1': 'Confidence to Control Diabetes', 'AB28_P1': 'Doctor Checked Feet for Sores', 'AB109': 'Visited ER', 
# 'AB113': 'Copy of Diabetes Care Plan', 'AB111': "Hospital Overnight for Diabetes"})

# corrMatrix = chis_train.corr()
# plt.subplots(figsize=(12, 9))
# g = sns.heatmap(corrMatrix, annot=True, cmap="Accent", vmin=-1, vmax=1)
# plt.title('Correlation Heatmap', size = 25)
# plt.show()



In [58]:
# from statsmodels.genmod.generalized_linear_model import GLM
# from statsmodels.genmod import families

# # Setup logistic regression model (using GLM method so that we can retrieve residuals)
# logit_model = GLM(y_train, X_constant, family=families.Binomial())
# logit_results = logit_model.fit()
# print(logit_results.summary())

In [59]:
# import scipy
# # Generate residual series plot
# fig = plt.figure(figsize=(15,9))
# ax = fig.add_subplot(111, title="Residual Series Plot",
#                     xlabel="Index Number", ylabel="Deviance Residuals")

# # ax.plot(X.index.tolist(), stats.zscore(logit_results.resid_pearson))
# ax.plot(X_constant.index.tolist(), scipy.stats.zscore(logit_results.resid_deviance))
# plt.axhline(y=0, ls="--", color='red');