In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import metrics_summary as ms

In [2]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

In [3]:
np.random.seed(170)

## SMOTE

In [4]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
os = SMOTE()
X_os, y_os = os.fit_resample(X_train, y_train)
print(X_os.shape, y_os.shape)

(236866, 763) (236866,)


In [5]:
# split the oversample data (keeping code for now in case we need it later)
# from sklearn.model_selection import train_test_split
# os_X_train, os_X_test, os_y_train, os_y_test = train_test_split(os_X, os_y, test_size=0.30, random_state=0)
# print(os_X_train.shape, os_y_train.shape)

## Logistic Regression

In [6]:
# check p-values of features
import statsmodels.api as sm
logit_model = sm.Logit(y_train, X_train)
result = logit_model.fit()
print(result.summary2())

c:\Users\Brian\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1810: RuntimeWarning: overflow encountered in exp
  return 1/(1+np.exp(-X))
c:\Users\Brian\anaconda3\lib\site-packages\statsmodels\discrete\discrete_model.py:1863: RuntimeWarning: divide by zero encountered in log
  return np.sum(np.log(self.cdf(q*np.dot(X,params))))


         Current function value: inf
         Iterations: 35


LinAlgError: Singular matrix

The feature with p-values less than 0.05 are the significant ones. Consider getting rid of insignificant features and then fit it into the logistic regression model

In [ ]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(logreg, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[49798   897]
 [ 3389  2653]]
Kappa Score: 0.5149340214729062
Accuracy Score: 0.9244584662565875
Precision: 0.7473239436619719
Recall: 0.4390930155577623
F1 Score: 0.5531693077564637
AUC Score: 0.7106994814449232


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.9225144890507107
Average Precision Score: 0.7509451078835438
Average Recall Score: 0.40306420149764544
Average F1 Score: 0.9225144890507107
Average AUC Score: 0.928102946487612


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.928102946487612

In [ ]:
logreg_cs = LogisticRegression(max_iter=1000, class_weight="balanced")
logreg_cs.fit(X_train, y_train)
y_pred = logreg_cs.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(logreg_cs, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[43991  6704]
 [ 1058  4984]]
Kappa Score: 0.49070440694665984
Accuracy Score: 0.8631933306308053
Precision: 0.4264202600958248
Recall: 0.8248924197285668
F1 Score: 0.5622109419063734
AUC Score: 0.8463252906414802


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.8716329809661998
Average Precision Score: 0.44352644935888746
Average Recall Score: 0.8382397850746575
Average F1 Score: 0.8716329809661998
Average AUC Score: 0.9361968100628928


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9361968100628928

#### Logistic Regression using oversampled data from SMOTE

In [ ]:
logreg_os = LogisticRegression(max_iter=1000)
logreg_os.fit(X_os, y_os)
y_pred = logreg_os.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(logreg_os, X_os, y_os)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[43852  6843]
 [ 1001  5041]]
Kappa Score: 0.490481059785041
Accuracy Score: 0.861748065636181
Precision: 0.42418377650622685
Recall: 0.8343263819927177
F1 Score: 0.5624232957715052
AUC Score: 0.8496713278934889


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.8678112839395359
Average Precision Score: 0.868505642788174
Average Recall Score: 0.8668696514441819
Average F1 Score: 0.8678112839395359
Average AUC Score: 0.9407807495625093


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9407807495625093

In [ ]:
# # Use variance inflation factor to identify any significant multi-collinearity
# from statsmodels.stats.outliers_influence import variance_inflation_factor
# X_constant = sm.add_constant(X_train, prepend=False)
# vif = pd.DataFrame()
# vif["Features"] = X_constant.columns
# vif["VIF"] = [variance_inflation_factor(X_constant.values, i) for i in range(X_constant.shape[1])]
# vif

In [ ]:
# sns.set(font_scale=1.25)
# # chis_train = pd.concat([X_train, y_train], axis=1)
# # chis_train = chis_train.rename(columns = {'T2D': 'Type 2 Diabetes', 'AB24': 'Taking Insulin', 'AB23_P1': 'Age Told To Have Diabetes', 'AB112': 'Diabetes Care Plan', 
# # 'AB25': 'Diabetic Pills', 'AB63': 'Eye Exam Dilated Pupils', 'AB114_P1': 'Confidence to Control Diabetes', 'AB28_P1': 'Doctor Checked Feet for Sores', 'AB109': 'Visited ER', 
# # 'AB113': 'Copy of Diabetes Care Plan', 'AB111': "Hospital Overnight for Diabetes"})

# corrMatrix = X_train.corr()
# plt.subplots(figsize=(24, 18))
# # g = sns.heatmap(corrMatrix, annot=True, cmap="Accent", vmin=-1, vmax=1)
# g = sns.heatmap(corrMatrix, annot=True, cmap="Accent")
# plt.title('Correlation Heatmap', size = 25)
# plt.show()



In [ ]:
from statsmodels.genmod.generalized_linear_model import GLM
from statsmodels.genmod import families

# Setup logistic regression model (using GLM method so that we can retrieve residuals)
logit_model = GLM(y_train, X_constant, family=families.Binomial())
logit_results = logit_model.fit()
print(logit_results.summary())

NameError: name 'X_constant' is not defined

In [ ]:
import scipy
# Generate residual series plot
fig = plt.figure(figsize=(15,9))
ax = fig.add_subplot(111, title="Residual Series Plot",
                    xlabel="Index Number", ylabel="Deviance Residuals")

# ax.plot(X.index.tolist(), stats.zscore(logit_results.resid_pearson))
ax.plot(X_constant.index.tolist(), scipy.stats.zscore(logit_results.resid_deviance))
plt.axhline(y=0, ls="--", color='red');