In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import metrics_summary as ms

In [2]:
np.random.seed(170)

In [3]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

## SMOTE

In [4]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
os = SMOTE()
X_os, y_os = os.fit_resample(X_train, y_train)
print(X_os.shape, y_os.shape)

(236780, 246) (236780,)


## XGBoost

In [5]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(xgb, X_train, y_train)

[[49552  1186]
 [ 4481  1518]]
Kappa Score: 0.3030543325294446
Accuracy Score: 0.9001180887251705
Precision: 0.5613905325443787
Recall: 0.25304217369561594
F1 Score: 0.34884522578421234
AUC Score: 0.6148335942387181
Average Accuracy Score: 0.8981085585092086
Average Precision Score: 0.540363405677103
Average Recall Score: 0.24342683611493898
Average F1 Score: 0.8981085585092086
[0.89848176 0.89541867 0.89723156 0.89998867 0.89942214]
Average AUC Score: 0.8750014761952313
[0.87057935 0.8736725  0.87646556 0.87626524 0.87802472]


#### XGBoost Using SMOTE

In [6]:
xgb_os = XGBClassifier()
xgb_os.fit(X_os, y_os)
y_pred = xgb_os.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(xgb_os, X_os, y_os)


[[49521  1217]
 [ 4493  1506]]
Kappa Score: 0.2990575771551396
Accuracy Score: 0.8993602058621358
Precision: 0.55306647080426
Recall: 0.2510418403067178
F1 Score: 0.345333639073607
AUC Score: 0.6135279365907431
Average Accuracy Score: 0.926940619984796
Average Precision Score: 0.9730412476271164
Average Recall Score: 0.8817805557901849
Average F1 Score: 0.926940619984796
[0.70445139 0.98213532 0.9827477  0.98306445 0.98230425]
Average AUC Score: 0.9782497362461235
[0.89125785 0.99999866 0.99999768 0.9999969  0.99999759]
