In [1]:
import pandas as pd
import numpy as np

import metrics_summary as ms

In [2]:
np.random.seed(170)

In [3]:
X_train = pd.read_csv("data/X_train.csv")
X_test = pd.read_csv("data/X_test.csv")
y_train = pd.read_csv("data/y_train.csv").values.ravel()
y_test = pd.read_csv("data/y_test.csv").values.ravel()

## XGBoost

In [4]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(xgb, X_train, y_train)

[[49546  1192]
 [ 4475  1524]]
Kappa Score: 0.30386443635188465
Accuracy Score: 0.9001180887251705
Precision: 0.561119293078056
Recall: 0.254042340390065
F1 Score: 0.34974182444061963
AUC Score: 0.6152745503046151
Average Accuracy Score: 0.8980330249137233
Average Precision Score: 0.5390561645976746
Average Recall Score: 0.24478447158352282
Average F1 Score: 0.8980330249137233
[0.89718779 0.89884203 0.89806925]
Average AUC Score: 0.8740520969035818
[0.87346255 0.87321228 0.87548146]


## XGBoost Using SMOTE

#### SMOTE

In [5]:
# implement SMOTE to oversample the minority class
from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
pipeline = Pipeline(steps=[('over', SMOTE()), ('model', XGBClassifier())])
pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
ms.metrics_summary(y_test, y_pred)
ms.crossval_summary(pipeline, X_train, y_train)

[[49559  1179]
 [ 4493  1506]]
Kappa Score: 0.30115175400381233
Accuracy Score: 0.9000299628108641
Precision: 0.5608938547486033
Recall: 0.2510418403067178
F1 Score: 0.34684477199447256
AUC Score: 0.6139024093724846
Average Accuracy Score: 0.8976628979375096
Average Precision Score: 0.5348625362583661
Average Recall Score: 0.24535610430949636
Average F1 Score: 0.8976628979375096
[0.89718779 0.89773165 0.89806925]
Average AUC Score: 0.8748020995625966
[0.8755567  0.87425761 0.87459199]
