In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import metrics_summary as ms

In [12]:
X_train = pd.read_csv("../../data/X_train.csv")
X_test = pd.read_csv("../data/X_test.csv")
y_train = pd.read_csv("../data/y_train.csv").values.ravel()
y_test = pd.read_csv("../data/y_test.csv").values.ravel()

In [13]:
np.random.seed(170)

## Logistic Regression

In [14]:
# check p-values of features
import statsmodels.api as sm
logit_model = sm.Logit(y_train, X_train)
result = logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.251318
         Iterations 8
                             Results: Logit
Model:                 Logit              Pseudo R-squared:   0.255     
Dependent Variable:    y                  AIC:                67027.9666
Date:                  2022-05-30 13:12   BIC:                69407.7816
No. Observations:      132386             Log-Likelihood:     -33271.   
Df Model:              242                LL-Null:            -44677.   
Df Residuals:          132143             LLR p-value:        0.0000    
Converged:             1.0000             Scale:              1.0000    
No. Iterations:        8.0000                                           
------------------------------------------------------------------------
             Coef.    Std.Err.     z     P>|z|     [0.025       0.975]  
------------------------------------------------------------------------
AB1          0.4971      0.0081  61.6194 0.0000    

The feature with p-values less than 0.05 are the significant ones. Consider getting rid of insignificant features and then fit it into the logistic regression model

In [22]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)
y_pred = logreg.predict(X_test)
y_prob = logreg.predict_proba(X_test)[:,1]
ms.metrics_summary(y_test, y_pred, y_prob)
ms.crossval_summary(logreg, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[50190   548]
 [ 5539   460]]
Kappa Score: 0.1040414821506156
Accuracy Score: 0.8927155119234362
Precision: 0.45634920634920634
Recall: 0.07667944657442907
F1 Score: 0.13129727415441703
AUC Score: 0.8101977505796738


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

KeyboardInterrupt: 

In [16]:
logreg_cs = LogisticRegression(max_iter=1000, class_weight="balanced")
logreg_cs.fit(X_train, y_train)
y_pred = logreg_cs.predict(X_test)
y_prob = logreg_cs.predict_proba(X_test)[:,1]
ms.metrics_summary(y_test, y_pred, y_prob)
ms.crossval_summary(logreg_cs, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[33838 16900]
 [ 1541  4458]]
Kappa Score: 0.19261798679694497
Accuracy Score: 0.6749740028552796
Precision: 0.20872740893342073
Recall: 0.7431238539756626
F1 Score: 0.3259129290492378
AUC Score: 0.7747758865115227


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.6731300465314135
Average Precision Score: 0.2069844616144645
Average Recall Score: 0.7387116827438371
Average F1 Score: 0.6731300465314135
[0.67878994 0.66993995 0.66748499 0.67379235 0.67564301]
Average AUC Score: 0.77283731822907
[0.772908   0.77341708 0.77168396 0.77052029 0.77565726]


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


#### Logistic Regression using oversampled data from SMOTE

In [17]:
# implement SMOTE to oversample the minority class
from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline
logreg_os = Pipeline(steps=[('over', SMOTE()), ('model', LogisticRegression(max_iter=1000))])
logreg_os.fit(X_train, y_train)
y_pred = logreg_os.predict(X_test)
y_prob = logreg_os.predict_proba(X_test)[:,1]
ms.metrics_summary(y_test, y_pred, y_prob)
ms.crossval_summary(logreg_os, X_train, y_train)

c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[[33835 16903]
 [ 1605  4394]]
Kappa Score: 0.1879745291001741
Accuracy Score: 0.6737931156035744
Precision: 0.20632013898671175
Recall: 0.7324554092348725
F1 Score: 0.32195193434935526
AUC Score: 0.7699789184646781


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_

Average Accuracy Score: 0.6785762700497567
Average Precision Score: 0.20817143971329694
Average Recall Score: 0.7272785688766396
Average F1 Score: 0.6785762700497567
[0.68048946 0.6875779  0.67575632 0.68247913 0.66657854]
Average AUC Score: 0.7717278051749935
[0.77393622 0.77470665 0.7702378  0.7729241  0.76683425]


c:\Users\Brian\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [18]:
# # Use variance inflation factor to identify any significant multi-collinearity
# from statsmodels.stats.outliers_influence import variance_inflation_factor
# X_constant = sm.add_constant(X_train, prepend=False)
# vif = pd.DataFrame()
# vif["Features"] = X_constant.columns
# vif["VIF"] = [variance_inflation_factor(X_constant.values, i) for i in range(X_constant.shape[1])]
# vif

In [19]:
# sns.set(font_scale=1.25)
# # chis_train = pd.concat([X_train, y_train], axis=1)
# # chis_train = chis_train.rename(columns = {'T2D': 'Type 2 Diabetes', 'AB24': 'Taking Insulin', 'AB23_P1': 'Age Told To Have Diabetes', 'AB112': 'Diabetes Care Plan', 
# # 'AB25': 'Diabetic Pills', 'AB63': 'Eye Exam Dilated Pupils', 'AB114_P1': 'Confidence to Control Diabetes', 'AB28_P1': 'Doctor Checked Feet for Sores', 'AB109': 'Visited ER', 
# # 'AB113': 'Copy of Diabetes Care Plan', 'AB111': "Hospital Overnight for Diabetes"})

# corrMatrix = X_train.corr()
# plt.subplots(figsize=(24, 18))
# # g = sns.heatmap(corrMatrix, annot=True, cmap="Accent", vmin=-1, vmax=1)
# g = sns.heatmap(corrMatrix, annot=True, cmap="Accent")
# plt.title('Correlation Heatmap', size = 25)
# plt.show()

In [20]:
# from statsmodels.genmod.generalized_linear_model import GLM
# from statsmodels.genmod import families

# # Setup logistic regression model (using GLM method so that we can retrieve residuals)
# logit_model = GLM(y_train, X_constant, family=families.Binomial())
# logit_results = logit_model.fit()
# print(logit_results.summary())

In [21]:
# import scipy
# # Generate residual series plot
# fig = plt.figure(figsize=(15,9))
# ax = fig.add_subplot(111, title="Residual Series Plot",
#                     xlabel="Index Number", ylabel="Deviance Residuals")

# # ax.plot(X.index.tolist(), stats.zscore(logit_results.resid_pearson))
# ax.plot(X_constant.index.tolist(), scipy.stats.zscore(logit_results.resid_deviance))
# plt.axhline(y=0, ls="--", color='red');